/* Generated by re2c 4.4 on Tue Mar 17 20:35:38 2026 */
#line 1 "pre_src/lexer.cpp"
#include <OllinAPI/Ollin.h>
#include <OllinAPI/lexer.h>


Token::Token() : type(Token::Type::UNKNOWN), value(""), col(0), ln(0) {}
Token::Token(Token::Type t, int c, int l, std::string v) : type(t), value(std::move(v)), col(c), ln(l) {}

const char* Token::toString(Token::Type t) {
    switch (t) {
        #define GENERATE_STRING(name) case Token::Type::name: return #name;
        TOKEN_TYPES(GENERATE_STRING)
        #undef GENERATE_STRING
        
        default: return "INVALID";
    }
}


int lex(const char* input, std::vector<Token>& tkn) {
    const char* YYCURSOR = input;
    const char* start;
    int ln = 1;
    int col = 1;


    while (*YYCURSOR) {
        start = YYCURSOR;

        
#line 33 "src/lexer/lexer.cpp"
{
	unsigned char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy2;
		case '\n':
		case '\r':
		case '?': goto yy4;
		case '!':
		case '%':
		case '&':
		case '*':
		case '+':
		case '-':
		case '/':
		case '<':
		case '=':
		case '>':
		case '^':
		case '|':
		case '~': goto yy5;
		case '"': goto yy6;
		case '\'': goto yy7;
		case '(': goto yy8;
		case ')': goto yy9;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy10;
		case ';': goto yy12;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		case 'c': goto yy16;
		case 'f': goto yy17;
		case 'i': goto yy18;
		case 'p': goto yy19;
		case 's': goto yy20;
		case '{': goto yy21;
		case '}': goto yy22;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
#line 149 "pre_src/lexer.cpp"
	{
                col += 1;
                ++YYCURSOR;
                continue;
            }
#line 136 "src/lexer/lexer.cpp"
yy2:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy2;
		default: goto yy3;
	}
yy3:
#line 33 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                continue;
            }
#line 150 "src/lexer/lexer.cpp"
yy4:
	++YYCURSOR;
#line 38 "pre_src/lexer.cpp"
	{
                col = 1;
                ln++;
                tkn.emplace_back(Token::Type::LN, ln, col);
                continue;
            }
#line 160 "src/lexer/lexer.cpp"
yy5:
	++YYCURSOR;
#line 125 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::OPERATOR, ln, col, std::string(start, YYCURSOR - start));
                continue;
            }
#line 169 "src/lexer/lexer.cpp"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy23;
		case '\\': goto yy24;
		default: goto yy6;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy25;
		case '\\': goto yy26;
		default: goto yy7;
	}
yy8:
	++YYCURSOR;
#line 51 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::LPARENT, ln, col);
                continue;
            }
#line 192 "src/lexer/lexer.cpp"
yy9:
	++YYCURSOR;
#line 58 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::RPARENT, ln, col);
                continue;
            }
#line 201 "src/lexer/lexer.cpp"
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy10;
		default: goto yy11;
	}
yy11:
#line 119 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::NUM, ln, col, std::string(start, YYCURSOR - start));
                continue;
            }
#line 224 "src/lexer/lexer.cpp"
yy12:
	++YYCURSOR;
#line 45 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::SEMICOLON, ln, col);
                continue;
            }
#line 233 "src/lexer/lexer.cpp"
yy13:
	yych = *++YYCURSOR;
yy14:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy15;
	}
yy15:
#line 131 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::IDENT, ln, col, std::string(start, YYCURSOR - start));
                continue;
            }
#line 310 "src/lexer/lexer.cpp"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy27;
		default: goto yy14;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy28;
		default: goto yy14;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy30;
		default: goto yy14;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy31;
		case 'u': goto yy32;
		default: goto yy14;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy33;
		default: goto yy14;
	}
yy21:
	++YYCURSOR;
#line 64 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::LBRACE, ln, col);
                continue;
            }
#line 350 "src/lexer/lexer.cpp"
yy22:
	++YYCURSOR;
#line 71 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::RBRACE, ln, col);
                continue;
            }
#line 359 "src/lexer/lexer.cpp"
yy23:
	++YYCURSOR;
#line 137 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::STRA, ln, col, std::string(start, YYCURSOR - start));
                continue;
            }
#line 368 "src/lexer/lexer.cpp"
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\\': goto yy24;
		default: goto yy6;
	}
yy25:
	++YYCURSOR;
#line 143 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::STRB, ln, col, std::string(start, YYCURSOR - start));
                continue;
            }
#line 383 "src/lexer/lexer.cpp"
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\\': goto yy26;
		default: goto yy7;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy34;
		default: goto yy14;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy29;
	}
yy29:
#line 77 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::FN, ln, col);
                continue;
            }
#line 471 "src/lexer/lexer.cpp"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy35;
		default: goto yy14;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy37;
		default: goto yy14;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'b': goto yy38;
		default: goto yy14;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy39;
		case 'r': goto yy40;
		default: goto yy14;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy41;
		default: goto yy14;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy36;
	}
yy36:
#line 83 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::INT, ln, col);
                continue;
            }
#line 578 "src/lexer/lexer.cpp"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy42;
		default: goto yy14;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy43;
		default: goto yy14;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy44;
		default: goto yy14;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy45;
		default: goto yy14;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy46;
		default: goto yy14;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy48;
		default: goto yy14;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy50;
		default: goto yy14;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy51;
		default: goto yy14;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy52;
		default: goto yy14;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy47;
	}
yy47:
#line 107 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::CLASS, ln, col);
                continue;
            }
#line 708 "src/lexer/lexer.cpp"
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy49;
	}
yy49:
#line 89 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::PRINT, ln, col);
                continue;
            }
#line 784 "src/lexer/lexer.cpp"
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy53;
		default: goto yy14;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy55;
		default: goto yy14;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy57;
		default: goto yy14;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy54;
	}
yy54:
#line 113 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::PUBLIC, ln, col);
                continue;
            }
#line 878 "src/lexer/lexer.cpp"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy56;
	}
yy56:
#line 95 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::STATIC, ln, col);
                continue;
            }
#line 954 "src/lexer/lexer.cpp"
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy58;
	}
yy58:
#line 101 "pre_src/lexer.cpp"
	{
                col += (YYCURSOR - start);
                tkn.emplace_back(Token::Type::STRING, ln, col);
                continue;
            }
#line 1030 "src/lexer/lexer.cpp"
}
#line 154 "pre_src/lexer.cpp"

    }

    return 0;
}