/* Generated by re2c 4.4 on Mon Mar 16 09:45:05 2026 */
#line 1 "pre_src/pre_Ollin.cpp"
#include <iostream>
#include <assert.h>
#include <map>
#include <string>
#include <fstream>
#include <vector>

struct Data
{
    std::string Value;
    int ln;
    int col;

    Data(int ln, int col, const std::string& Value = "") 
        : Value(Value), ln(ln), col(col) {}
};

struct Token {
    std::string type;
    Data data;

    Token() : type(""), data(0, 0) {}
    Token(const std::string& t, const Data& d) 
        : type(t), data(d) {}
    Token(const std::string& t, int ln, int col, const std::string& value = "") 
        : type(t), data(ln, col, value) {}
};

    
int lex(const char* input, std::vector<Token>& tkn) {
        const char* YYCURSOR = input;
        const char* start;
        int ln = 1;
        int col = 1;
        
        
        while (*YYCURSOR) {
            start = YYCURSOR;
            
            
#line 44 "src/Ollin.cpp"
{
	unsigned char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy2;
		case '\n':
		case '\r':
		case '?': goto yy4;
		case '!':
		case '%':
		case '&':
		case '*':
		case '+':
		case '-':
		case '/':
		case '<':
		case '=':
		case '>':
		case '^':
		case '|':
		case '~': goto yy5;
		case '"': goto yy6;
		case '\'': goto yy7;
		case '(': goto yy8;
		case ')': goto yy9;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy10;
		case ';': goto yy12;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		case 'c': goto yy16;
		case 'f': goto yy17;
		case 'i': goto yy18;
		case 'p': goto yy19;
		case 's': goto yy20;
		case '{': goto yy21;
		case '}': goto yy22;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
#line 167 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                ++YYCURSOR;
                continue;
            }
#line 147 "src/Ollin.cpp"
yy2:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy2;
		default: goto yy3;
	}
yy3:
#line 46 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                continue;
            }
#line 161 "src/Ollin.cpp"
yy4:
	++YYCURSOR;
#line 51 "pre_src/pre_Ollin.cpp"
	{
                col = 1;
                ln++;
                tkn.push_back({"LN", Data(ln, col)});
                continue;
            }
#line 171 "src/Ollin.cpp"
yy5:
	++YYCURSOR;
#line 139 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                std::string m(start, YYCURSOR - start);
                tkn.push_back({"OPERATOR", Data(ln, col, m)});
                continue;
            }
#line 181 "src/Ollin.cpp"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy23;
		case '\\': goto yy24;
		default: goto yy6;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy25;
		case '\\': goto yy26;
		default: goto yy7;
	}
yy8:
	++YYCURSOR;
#line 64 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"LPARENT", Data(ln, col)});
                continue;
            }
#line 204 "src/Ollin.cpp"
yy9:
	++YYCURSOR;
#line 71 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"RPARENT", Data(ln, col)});
                continue;
            }
#line 213 "src/Ollin.cpp"
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy10;
		default: goto yy11;
	}
yy11:
#line 132 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                std::string m(start, YYCURSOR - start);
                tkn.push_back({"NUM", Data(ln, col, m)});
                continue;
            }
#line 237 "src/Ollin.cpp"
yy12:
	++YYCURSOR;
#line 58 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"SEMICOLON", Data(ln, col)});
                continue;
            }
#line 246 "src/Ollin.cpp"
yy13:
	yych = *++YYCURSOR;
yy14:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy15;
	}
yy15:
#line 146 "pre_src/pre_Ollin.cpp"
	{
                std::string m(start, YYCURSOR - start);
                col += (YYCURSOR - start);
                tkn.push_back({"IDENT", Data(ln, col, m)});
                continue;
            }
#line 324 "src/Ollin.cpp"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy27;
		default: goto yy14;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy28;
		default: goto yy14;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy30;
		default: goto yy14;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy31;
		case 'u': goto yy32;
		default: goto yy14;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy33;
		default: goto yy14;
	}
yy21:
	++YYCURSOR;
#line 77 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"LBRACE", Data(ln, col)});
                continue;
            }
#line 364 "src/Ollin.cpp"
yy22:
	++YYCURSOR;
#line 84 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"RBRACE", Data(ln, col)});
                continue;
            }
#line 373 "src/Ollin.cpp"
yy23:
	++YYCURSOR;
#line 153 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                std::string m(start, YYCURSOR - start);
                tkn.push_back({"STRING", Data(ln, col, m)});
                continue;
            }
#line 383 "src/Ollin.cpp"
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\\': goto yy24;
		default: goto yy6;
	}
yy25:
	++YYCURSOR;
#line 160 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                std::string m(start, YYCURSOR - start);
                tkn.push_back({"STRING", Data(ln, col, m)});
                continue;
            }
#line 399 "src/Ollin.cpp"
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\\': goto yy26;
		default: goto yy7;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy34;
		default: goto yy14;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy29;
	}
yy29:
#line 90 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"FN", Data(ln, col)});
                continue;
            }
#line 487 "src/Ollin.cpp"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy35;
		default: goto yy14;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy37;
		default: goto yy14;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'b': goto yy38;
		default: goto yy14;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy39;
		case 'r': goto yy40;
		default: goto yy14;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy41;
		default: goto yy14;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy36;
	}
yy36:
#line 96 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"INT", Data(ln, col)});
                continue;
            }
#line 594 "src/Ollin.cpp"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy42;
		default: goto yy14;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy43;
		default: goto yy14;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy44;
		default: goto yy14;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy45;
		default: goto yy14;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy46;
		default: goto yy14;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy48;
		default: goto yy14;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy50;
		default: goto yy14;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy51;
		default: goto yy14;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy52;
		default: goto yy14;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy47;
	}
yy47:
#line 120 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"CLASS", Data(ln, col)});
                continue;
            }
#line 724 "src/Ollin.cpp"
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy49;
	}
yy49:
#line 102 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"PRINT", Data(ln, col)});
                continue;
            }
#line 800 "src/Ollin.cpp"
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy53;
		default: goto yy14;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy55;
		default: goto yy14;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy57;
		default: goto yy14;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy54;
	}
yy54:
#line 126 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"PUBLIC", Data(ln, col)});
                continue;
            }
#line 894 "src/Ollin.cpp"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy56;
	}
yy56:
#line 108 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"STATIC", Data(ln, col)});
                continue;
            }
#line 970 "src/Ollin.cpp"
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy13;
		default: goto yy58;
	}
yy58:
#line 114 "pre_src/pre_Ollin.cpp"
	{
                col += (YYCURSOR - start);
                tkn.push_back({"STRING", Data(ln, col)});
                continue;
            }
#line 1046 "src/Ollin.cpp"
}
#line 172 "pre_src/pre_Ollin.cpp"

    }

    return 0;
}

int main() {

    std::ifstream file("test.ollin", std::ios::binary);

    std::string content(
        (std::istreambuf_iterator<char>(file)),
        std::istreambuf_iterator<char>()
    );

    std::vector<Token> Tokens;
    int res = lex(content.data(), Tokens);
    
    if (res != 0) {
        return 1;
    }
    
    std::cout << "code :" << std::endl;
    std::cout << "------------------------------" << std::endl;
    std::cout << content << std::endl;
    std::cout << "------------------------------" << std::endl;
    std::cout << std::endl;
    
    std::cout << "------------------------------" << std::endl;
    std::cout << "Token Zise: " << Tokens.size() << std::endl;
    std::cout << "------------------------------" << std::endl;
    std::cout << std::endl;

    for (const Token& t : Tokens) {
        if (t.data.Value == "") {
            std::cout << "Type: " << t.type << " --- " << "(" << t.data.col << ", " << t.data.ln << ")" << std::endl;
        } else {
            std::cout << "Type: " << t.type << " | " << "Value: " << t.data.Value << " --- " << "(" << t.data.col << ", " << t.data.ln << ")" << std::endl;
        }
    }

    

    return 0;
}

